### ISSUE TITLE
新内容

### ISSUE THREAD

**Issue by YunDouYue** [Shiroiame-Kusu/bwmc.live#26]
什么时候帮可爱的糖宝也写一个
![img](https://tangbao-1301296093.cos.ap-shanghai.myqcloud.com/blog/bqb/5OAWNP~8U049U6Z%24UYB7%60YU.jpg)

**Comment by Shiroiame-Kusu** [comment]
嘤，你都没有加我的友链

**Comment by YunDouYue** [comment]
> 嘤，你都没有加我的友链

什么叫没加，明明是你没加，横
![img](https://tangbao-1301296093.cos.ap-shanghai.myqcloud.com/blog/bqb/T%7D3M%5DTSQ%7D3%60WTH7%40JM6I~%606.gif)

**Comment by Shiroiame-Kusu** [comment]
那我加，你也要加！

**Comment by YunDouYue** [comment]
> 那我加，你也要加！

我明明早就加了，呜呜呜
![image](https://user-images.githubusercontent.com/85783168/183629415-5a03356e-c142-4590-a53b-b7d20d681c6a.png)

**Comment by Shiroiame-Kusu** [comment]
加了加了，嘤

**Comment by YunDouYue** [comment]
> 加了加了，嘤

真的吗，骗人可是不对的
![image](https://user-images.githubusercontent.com/85783168/183630128-e5b0d1b3-187c-4065-8ecd-15f64bf3a3a7.png)
![3EZ@YMX81F5MAABVM_QON 2](https://user-images.githubusercontent.com/85783168/183630162-c1e36035-3eb6-4727-8a54-414624984b16.gif)

**Comment by Shiroiame-Kusu** [comment]
是真的是真的，在清cache了

**Comment by YunDouYue** [comment]
> 是真的是真的，在清cache了

![5E_YX7XG5W 82O(NGWCQH82](https://user-images.githubusercontent.com/85783168/183630490-0da458a3-8827-412e-8203-a86008a38bf6.jpg)

**Comment by Shiroiame-Kusu** [comment]
嘤
