### ISSUE TITLE
有点问题....

### ISSUE THREAD

**Issue by tudou-OuO** [Shiroiame-Kusu/bwmc.live#53]
整体主题真的很喜欢！确实是改的很好，css更有逻辑，并添加json方便配置！（tips：在json生效前主要看index.html里的内容，会导致标题是kusunoki的情况，还是说一下为好）
  音乐播放器问题就....想自定义的，因为左边那么多东西想直接删掉，删掉<div id="current-version">时导致无法关闭该窗口（current-version位于main.js第378行），不删的话就会有个蓝色的更新按钮....你故意的，对吧（）
删掉之后，我想把播放器box放大，却发现不管怎么改参数这B玩意永远在大白框子里右边50%的位置，望修复！（或者是我没找到参数qwq）

**Comment by Shiroiame-Kusu** [comment]
你该重修html和js

**Comment by tudou-OuO** [comment]
你好，js没学过，所以告诉我怎么改（


土豆OuO
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shiroiame-Kusu/Kusunoki"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 晚上6:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Shiroiame-Kusu/Kusunoki] 有点问题.... (Issue #53)





 
你该重修html和js

**Comment by Shiroiame-Kusu** [comment]
你先这样，然后再这样，之后再这样，最后再这样，不就这样了吗

**Comment by tudou-OuO** [comment]
所以能不能告诉我音乐播放器怎么全覆盖窗口（恼
